version: '3'
services:
  e-commerce:
    build: .
    container_name: e-commerce-app
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      - ecommerce-db
  ecommerce-db:
    image: postgres:12.6
    env_file:
      - .env
    container_name: e-commerce-db
    command: postgres -c 'max_connections=300'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
