services:
  ecommerce-db:
    image: postgres:12.6
    container_name: e-commerce-database
    command: postgres -c 'max_connections=300'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres